-- deletes a cohort
SET @cohortIdTxt = :groupId;

SET @cohortId = (SELECT ID FROM COHORT WHERE ID_TXT = @cohortIdTxt);

DELETE FROM COHORT_SHOPPER_RELATION
WHERE COHORT_ID = @cohortId
;

UPDATE LIST
SET COHORT_ID = NULL
WHERE COHORT_ID = @cohortId
;

DELETE FROM COHORT
WHERE ID = @cohortId
;
