-- gets all the cohorts for the shopper ID
-- associated with the user

SET @shopperId = UUID_TO_BIN(:shopperId);

SELECT
  BIN_TO_UUID(c.ID) AS ID,
  c.NAME,
  BIN_TO_UUID(c.OWNER_ID) AS OWNER_ID,
  sh.NICKNAME AS OWNER_NICKNAME,
  sh.EMAIL AS OWNER_EMAIL
FROM PANTRY_PLUS.SHOPPER sh
JOIN PANTRY_PLUS.COHORT_SHOPPER_RELATION csr ON csr.SHOPPER_ID = sh.ID
JOIN PANTRY_PLUS.COHORT c ON c.ID = csr.COHORT_ID
WHERE sh.ID = @shopperId
UNION
SELECT
  BIN_TO_UUID(c.ID) AS ID,
  c.NAME,
  BIN_TO_UUID(c.OWNER_ID) AS OWNER_ID,
  sh.NICKNAME AS OWNER_NICKNAME,
  sh.EMAIL AS OWNER_EMAIL
FROM PANTRY_PLUS.COHORT c
WHERE c.OWNER_ID = @shopperId
;
