SET @categoryIdTxt = :categoryId;

SELECT BIN_TO_UUID(ITEM.ID) as ID, ITEM.NAME, ITEM.UPC
FROM ITEM_CATEGORY_RELATION
JOIN ITEM ON ITEM_CATEGORY_RELATION.ITEM_ID = ITEM.ID
WHERE CATEGORY_ID = UUID_TO_BIN(@categoryIdTxt)
;